[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_minimal.py"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "always"

[environments.production.variables]
PYTHON_UNBUFFERED = "1"
PORT = "8000"
