[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_railway_worker.py"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_UNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
