[build]
builder = "nixpacks"

[deploy]
startCommand = "./start_railway.sh"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_UNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
