[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_simple.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[environments.production.variables]
PYTHON_UNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
PORT = "8000"
