services:
  - type: worker
    name: trading-bot-worker
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: python run_render_worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: IS_RENDER
        value: "true"
      - key: TRADING_MODE
        value: "paper"
      - key: BINANCE_TESTNET
        value: "true"
      - key: PAPER_TRADING_INITIAL_BALANCE
        value: "20"
      - key: AI_ENABLED
        value: "false"
      - key: MAX_TRADES_PER_DAY
        value: "3"
      - key: RISK_PER_TRADE
        value: "0.015"
    autoDeploy: true
    preDeployCommand: echo "Starting Render deployment..."
